#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop, encoderPort, None)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex393_MC29, openLoop, encoderPort, None)
#pragma config(Motor,  port9,           servoMotor,    tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	setServo(servoMotor, -127); // start servo motor,turn left
	wait(2); // wait 2 seconds
	setServo(servoMotor, 0); // stop servo motor
	wait(2); // wait 2 seconds
	setServo(servoMotor, 127); // start servo motor, turn right
	wait(2); // wait 2 seconds.
}
