#pragma config(Sensor, dgtl12, green,          sensorLEDtoVCC)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           servoMotor,    tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
startMotor(rightMotor, 62);//start motor
StartMotor(leftMotor, 62)//start left motor
wait(5);//wait 5 sec
stopMotor(leftMotor);//stop left motor

stopMotor(rightMotor);//stop right motor




}
