#pragma config(Sensor, dgtl12, green,          sensorLEDtoVCC)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port9,           ser,           tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	startMotor(rightMotor, 63); //starts right motor at half speed foward
	wait(5);//waits 5 seconds
	stopMotor(rightMotor);//stops right motor
	startMotor(leftMotor, -100);//starts left motor at 3/4 speed reverse
	wait(2.5);//waits 2.5 seconds
	stopMotor(leftMotor);//stops left motor
	startMotor(rightMotor, 127);//starts right motor at full speed foward
	startMotor(leftMotor, 127);//starts left motor at full speed foward
	wait(7.5);//waits 7.5 seconds
	stopMotor(leftMotor);//stops left motor
	stopMotor(rightMotor);//stops rigt motor
}
