#pragma config(Sensor, dgtl1,  Encoder,        sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  bumpSwitch,     sensorTouch)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port4,           CMotor,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           CMotor2,       tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	untilBump(bumpSwitch, 1);


	startMotor(rightMotor, 50);//move forward
	startMotor(leftMotor, -46);//move forward
	wait(13);//for x seconds
	stopMotor(rightMotor);//stop the motor
	stopMotor(leftMotor);//stop the motor
	wait(1);//for x seconds
	startMotor(CMotor, 127); //rotates out of way
	wait(2); //rotates out of way
	stopMotor(CMotor); //stop motor

	startMotor(rightMotor, 60);//turn 180 degrees
	startMotor(leftMotor, 60);//turn 180 degrees
	wait(5);//for x seconds
	startMotor(rightMotor, 50);//move forward
	startMotor(leftMotor, -46);//move forward
	wait(13); //for x seconds
	stopMotor(rightMotor);//stop the motor
	stopMotor(leftMotor);//stop the motor

}
