#pragma config(Sensor, dgtl1,  Encoder,        sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  bumpSwitch,     sensorTouch)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port4,           CMotor,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           CMotor2,       tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	untilBump(bumpSwitch, 1);
	SensorValue(Encoder) = 0;

	startMotor(rightMotor, 50);//move forward
	startMotor(leftMotor, -50);//move forward
	wait(2);//for x seconds
	stopMotor(rightMotor);//stop the motor
	stopMotor(leftMotor);//stop the motor
	wait(1);//for x seconds
	startMotor(CMotor, 127);
	startMotor(CMotor2, -127);
	wait(1); //wait x seconds


if (SensorValue(Encoder) > 95)
	stopMotor(CMotor);
	stopMotor(CMotor2);



	startMotor(rightMotor, 40);//turn 180 degrees
	startMotor(leftMotor, 40);//turn 180 degrees
	wait(5);//for x seconds
	startMotor(rightMotor, 70);//move forward
	startMotor(leftMotor, -70);//move forward
	wait(2); //for x seconds
	stopMotor(rightMotor);//stop the motor
	stopMotor(leftMotor);//stop the motor

}
